### ISSUE TITLE
Typing version should display the tagged release version no

### ISSUE THREAD

**Issue by abhijit-mahajani-imgtec** [FlowM2M/u-boot#26]
Currently for 1.0.3 tagged release of uboot, its showing 
U-Boot 2015.10 (Dec 09 2016 - 10:51:44 +0000), Build: jenkins-CreatorDev-openwrt-ci40-128

Showing jenkins-CreatorDev-openwrt-ci40-128 does not help to end user, rather we should display the tagged release version no say 1.0.3 or show the git hash similar to what we show in built image of uboot from the uboot sources standalone.

**Comment by Ham22** [comment]
There are two issues I see.

First issue is that the version is being set using 'git describe' but by default it only picks up tags if they are annotated therefore its not picking up ours and instead falling all the way back to the branch of 2015.10. Simple fix is to annotate the tags? Or we could just mod the u-boot code to add the --tags option to pick up all tags.

Second issue BUILD_TAG is set by Jenkins causing the build identity to be set' Build: jenkins-CreatorDev-openwrt-ci40-128'. I feel this is quite useful for CI builds but we could certainly add something to the Jenkinsfile to unset the variable when a release build is created (i.e. when the build param VERSION is filled in unset BUILD_TAG).
